# Generated by Django 3.1.3 on 2020-11-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/placeholder.jpg', upload_to='images/'),
        ),
    ]
