# Generated by Django 3.1.3 on 2020-11-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/images/placeholder.jpg', upload_to='images/'),
        ),
    ]
